# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 300, 111, 20))
        self.label_4.setObjectName("label_4")
        self.BTN_DECRYPT = QtWidgets.QToolButton(self.centralwidget)
        self.BTN_DECRYPT.setGeometry(QtCore.QRect(340, 430, 81, 41))
        self.BTN_DECRYPT.setObjectName("BTN_DECRYPT")
        self.TXT_PLAINTEXT = QtWidgets.QTextEdit(self.centralwidget)
        self.TXT_PLAINTEXT.setGeometry(QtCore.QRect(140, 100, 301, 111))
        self.TXT_PLAINTEXT.setObjectName("TXT_PLAINTEXT")
        self.TXT_CIPHERTEXT = QtWidgets.QTextEdit(self.centralwidget)
        self.TXT_CIPHERTEXT.setGeometry(QtCore.QRect(140, 290, 301, 111))
        self.TXT_CIPHERTEXT.setObjectName("TXT_CIPHERTEXT")
        self.BTN_ENCRYPT = QtWidgets.QToolButton(self.centralwidget)
        self.BTN_ENCRYPT.setGeometry(QtCore.QRect(170, 430, 81, 41))
        self.BTN_ENCRYPT.setObjectName("BTN_ENCRYPT")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 10, 211, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 111, 20))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 110, 131, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(500, 300, 121, 20))
        self.label_6.setObjectName("label_6")
        self.TXT_INFORMATION = QtWidgets.QTextEdit(self.centralwidget)
        self.TXT_INFORMATION.setGeometry(QtCore.QRect(630, 100, 301, 111))
        self.TXT_INFORMATION.setObjectName("TXT_INFORMATION")
        self.TXT_SIGNATURE = QtWidgets.QTextEdit(self.centralwidget)
        self.TXT_SIGNATURE.setGeometry(QtCore.QRect(630, 290, 301, 111))
        self.TXT_SIGNATURE.setObjectName("TXT_SIGNATURE")
        self.BTN_SIGN = QtWidgets.QToolButton(self.centralwidget)
        self.BTN_SIGN.setGeometry(QtCore.QRect(650, 430, 81, 41))
        self.BTN_SIGN.setObjectName("BTN_SIGN")
        self.BTN_VERIFY = QtWidgets.QToolButton(self.centralwidget)
        self.BTN_VERIFY.setGeometry(QtCore.QRect(830, 430, 81, 41))
        self.BTN_VERIFY.setObjectName("BTN_VERIFY")
        self.BTN_GENERATE = QtWidgets.QToolButton(self.centralwidget)
        self.BTN_GENERATE.setGeometry(QtCore.QRect(650, 10, 151, 41))
        self.BTN_GENERATE.setObjectName("BTN_GENERATE")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1150, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">CIPHER TEXT</span></p></body></html>"))
        self.BTN_DECRYPT.setText(_translate("MainWindow", "Decrypt"))
        self.BTN_ENCRYPT.setText(_translate("MainWindow", "Encrypt"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; text-decoration: underline;\">RSA CIPHER</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">PLAIN TEXT</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">INFORMATION</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">SIGNATURE</span></p></body></html>"))
        self.BTN_SIGN.setText(_translate("MainWindow", "SIGN"))
        self.BTN_VERIFY.setText(_translate("MainWindow", "VERIFY"))
        self.BTN_GENERATE.setText(_translate("MainWindow", "GENERATE KEYS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
